/**
 * CRTD (CAN Real-Time Data) File Parser
 *
 * Parses .crtd files generated by gcgui live capture.
 *
 * Format:
 * Line 1: Header - "CXXRTL gcgui live capture <ISO timestamp>"
 * Subsequent lines: "<timestamp> <can_id> <data_bytes...>"
 *
 * Example:
 * CXXRTL gcgui live capture 2026-03-29T16:24:25.879Z
 * 4611.387 R11 36 7D 96 4F 03 B1 97 38 23
 * 4611.430 R29 00001F2C 02 06 22 00 6A 00 FF FF
 */

/**
 * Parse a CRTD file content string into an array of CAN messages
 * @param {string} content - Raw file content
 * @returns {Object} Parsed data with header and messages
 */
export function parseCRTD(content) {
    const lines = content.split("\n").filter(line => line.trim());

    if (lines.length === 0) {
        return { header: null, messages: [] };
    }

    // Parse header
    const headerLine = lines[0];
    let header = null;

    if (headerLine.startsWith("CXXRTL")) {
        header = {
            raw: headerLine,
            timestamp: headerLine.replace("CXXRTL gcgui live capture ", ""),
        };
    }

    // Parse CAN messages
    const messages = [];

    for (let i = 1; i < lines.length; i++) {
        const line = lines[i].trim();
        if (!line) continue;

        const message = parseCRTDLine(line);
        if (message) {
            messages.push(message);
        }
    }

    return { header, messages };
}

/**
 * Parse a single CRTD line into a CAN message object
 * @param {string} line - Single line from CRTD file
 * @returns {Object|null} Parsed CAN message or null if invalid
 */
function parseCRTDLine(line) {
    // Expected format: "<timestamp> <can_id> <data_bytes...>"
    // Example: "4611.387 R11 36 7D 96 4F 03 B1 97 38 23"
    // Example: "4611.430 R29 00001F2C 02 06 22 00 6A 00 FF FF"

    const parts = line.split(/\s+/);

    if (parts.length < 3) {
        return null;
    }

    const timestamp = parseFloat(parts[0]);
    if (isNaN(timestamp)) {
        return null;
    }

    // CAN ID might have R/T prefix (Received/Transmitted)
    let canId = parts[1];
    let direction = "R"; // Default to Received

    if (canId.startsWith("R") || canId.startsWith("T")) {
        direction = canId[0];
        canId = canId.substring(1);
    }

    // Parse data bytes (everything after CAN ID)
    const dataBytes = [];
    for (let i = 2; i < parts.length; i++) {
        const byte = parseInt(parts[i], 16);
        if (!isNaN(byte)) {
            dataBytes.push(byte);
        }
    }

    if (dataBytes.length === 0) {
        return null;
    }

    // Convert CAN ID to standard format (with 0x prefix)
    const canIdNum = parseInt(canId, 16);
    const formattedCanId = "0x" + canIdNum.toString(16).toLowerCase();

    return {
        timestamp,
        direction,
        canId: formattedCanId,
        canIdRaw: canId,
        dataBytes,
        raw: line,
    };
}

/**
 * Read and parse a CRTD file
 * @param {File} file - File object from input
 * @returns {Promise<Object>} Promise resolving to parsed CRTD data
 */
export function readCRTDFile(file) {
    return new Promise((resolve, reject) => {
        const reader = new FileReader();

        reader.onload = event => {
            try {
                const content = event.target.result;
                const parsed = parseCRTD(content);
                resolve(parsed);
            } catch (error) {
                reject(new Error(`Failed to parse CRTD file: ${error.message}`));
            }
        };

        reader.onerror = () => {
            reject(new Error("Failed to read file"));
        };

        reader.readAsText(file);
    });
}

/**
 * Format a CAN message back to CRTD line format
 * @param {Object} message - Parsed CAN message object
 * @returns {string} CRTD formatted line
 */
export function formatCRTDLine(message) {
    const { timestamp, direction, canIdRaw, dataBytes } = message;
    const dataHex = dataBytes.map(b => b.toString(16).toUpperCase().padStart(2, "0")).join(" ");
    return `${timestamp} ${direction}${canIdRaw} ${dataHex}`;
}

export default {
    parseCRTD,
    readCRTDFile,
    formatCRTDLine,
};
