/**
 * CSV Log Parser
 *
 * Parses `.csv` files generated by gcgui live capture (raw CSV output).
 *
 * Format:
 * Line 1 (optional): Comment - "# gcgui csv live capture <ISO timestamp>"
 * Subsequent lines: raw CSV - "<time>, <value1>, <value2>, ..."
 *
 * Example:
 * # gcgui csv live capture 2026-09-26T13:40:00.000Z
 * 12.345, 512, 23.7
 * 12.545, 508, 23.8
 *
 * Replay timing uses the first column as the timestamp (seconds) when it is
 * numeric. Lines without a numeric first column fall back to even 100 ms
 * spacing so they still replay in order.
 */

const FALLBACK_INTERVAL_S = 0.1;

/**
 * Parse a CSV log content string into replayable messages
 * @param {string} content - Raw file content
 * @returns {Object} Parsed data with header and messages
 */
export function parseCSVLog(content) {
    const lines = content.split("\n");

    if (lines.length === 0) {
        return { header: null, messages: [] };
    }

    let header = null;
    const messages = [];
    let lastTimestamp = 0;
    let hasTimestamp = false;

    for (const rawLine of lines) {
        const line = rawLine.replace(/\r$/, "").trim();
        if (!line) continue;
        // Skip comment / provenance headers from live capture
        if (line.startsWith("#") || line.startsWith("CXX")) continue;
        // Only CSV lines (raw serial output may contain stray text)
        if (!line.includes(",")) continue;

        const message = parseCSVLogLine(line, hasTimestamp ? lastTimestamp + FALLBACK_INTERVAL_S : 0);
        if (message) {
            messages.push(message);
            lastTimestamp = message.timestamp;
            hasTimestamp = true;
        }
    }

    // Detect a leading comment header for display purposes
    const firstLine = lines[0] != null ? lines[0].replace(/\r$/, "").trim() : "";
    if (firstLine.startsWith("#")) {
        header = { raw: firstLine };
    }

    return { header, messages };
}

/**
 * Parse a single CSV log line into a replayable message object
 * @param {string} line - Single CSV line, e.g. "12.345, 512, 23.7"
 * @param {number} fallbackTimestamp - Timestamp when the first column is not numeric
 * @returns {Object|null} Parsed message or null if not a CSV line
 */
export function parseCSVLogLine(line, fallbackTimestamp = 0) {
    const trimmed = line.replace(/\r$/, "").trim();
    if (!trimmed || !trimmed.includes(",")) {
        return null;
    }

    const cells = trimmed.split(",").map(cell => cell.trim());
    if (cells.length < 2) {
        return null;
    }

    const first = parseFloat(cells[0]);
    const timestamp = Number.isFinite(first) ? first : fallbackTimestamp;

    return {
        kind: "csv",
        timestamp,
        raw: trimmed,
    };
}

/**
 * Read and parse a CSV log file
 * @param {File} file - File object from input
 * @returns {Promise<Object>} Promise resolving to parsed CSV log data
 */
export function readCSVLogFile(file) {
    return new Promise((resolve, reject) => {
        const reader = new FileReader();

        reader.onload = event => {
            try {
                const content = event.target.result;
                const parsed = parseCSVLog(content);
                resolve(parsed);
            } catch (error) {
                reject(new Error(`Failed to parse CSV file: ${error.message}`));
            }
        };

        reader.onerror = () => {
            reject(new Error("Failed to read file"));
        };

        reader.readAsText(file);
    });
}

/**
 * Format a CSV message back to raw line format (injectable as serial data)
 * @param {Object} message - Parsed CSV message object
 * @returns {string} Raw CSV line
 */
export function formatCSVLine(message) {
    return message.raw;
}

export default {
    parseCSVLog,
    parseCSVLogLine,
    readCSVLogFile,
    formatCSVLine,
};
